version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: verifiable_stubs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verifiable_stubs
    ports:
      - "5433:5432"   # ðŸ‘ˆ CHANGED
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
